version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: nginx_web_1
      APP_PORT: 80

  web:
    image: nginx:latest
    volumes:
      - "${APP_DATA_DIR}/www/html:/usr/share/nginx/html"
    restart: on-failure