version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: orho-nginx_web_1
      APP_PORT: 80

  web:
    image: nginx:latest
    restart: unless-stopped

    volumes:
      - "${APP_DATA_DIR}/www/html:/usr/share/nginx/html"
      - "${APP_DATA_DIR}/nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "${APP_DATA_DIR}/nginx/conf.d:/etc/nginx/conf.d"
      - "${APP_DATA_DIR}/nginx/logs:/var/log/nginx"
