version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: orho-nginx
      APP_PORT: 80

  web:
    image: nginx:latest
    container_name: orho-nginx
    restart: unless-stopped

    volumes:
      - "${APP_DATA_DIR}/www/html:/usr/share/nginx/html:ro"
      - "${APP_DATA_DIR}/nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "${APP_DATA_DIR}/nginx/conf.d:/etc/nginx/conf.d:ro"
      - "${APP_DATA_DIR}/nginx/logs:/var/log/nginx"
      
